#!/bin/ash 

echo -n "2	"; sleep .05
echo -n "3	"; sleep .05
echo -n "5	"; sleep .05
echo -n "7	"; sleep .05
echo -n "11	"; sleep .05
echo -n "13	"; sleep .05
echo -n "17	"; sleep .05
echo -n "19	"; sleep .05
echo -n "23	"; sleep .05
echo  "29	"; sleep .05
echo -n "31	"; sleep .05
echo -n "37	"; sleep .05
echo -n "41	"; sleep .05
echo -n "43	"; sleep .05
echo -n "47	"; sleep .05
echo -n "53	"; sleep .05
echo -n "59	"; sleep .05
echo -n "61	"; sleep .05
echo -n "67	"; sleep .05
echo  "71	"; sleep .05
echo -n "73	"; sleep .05
echo -n "79	"; sleep .05
echo -n "83	"; sleep .05
echo -n "89	"; sleep .05
echo -n "97	"; sleep .05
echo -n "101	"; sleep .05
echo -n "103	"; sleep .05
echo -n "107	"; sleep .05
echo -n "109	"; sleep .05
echo  "113	"; sleep .05
echo -n "127	"; sleep .05
echo -n "131	"; sleep .05
echo -n "137	"; sleep .05
echo -n "139	"; sleep .05
echo -n "149	"; sleep .05
echo -n "151	"; sleep .05
echo -n "157	"; sleep .05
echo -n "163	"; sleep .05
echo -n "167	"; sleep .05
echo  "173	"; sleep .05
echo -n "179	"; sleep .05
echo -n "181	"; sleep .05
echo -n "191	"; sleep .05
echo -n "193	"; sleep .05
echo -n "197	"; sleep .05
echo -n "199	"; sleep .05
echo -n "211	"; sleep .05
echo -n "223	"; sleep .05
echo -n "227	"; sleep .05
echo  "229	"; sleep .05
echo -n "233	"; sleep .05
echo -n "239	"; sleep .05
echo -n "241	"; sleep .05
echo -n "251	"; sleep .05
echo -n "257	"; sleep .05
echo -n "263	"; sleep .05
echo -n "269	"; sleep .05
echo -n "271	"; sleep .05
echo -n "277	"; sleep .05
echo  "281	"; sleep .05
echo -n "283	"; sleep .05
echo -n "293	"; sleep .05
echo -n "307	"; sleep .05
echo -n "311	"; sleep .05
echo -n "313	"; sleep .05
echo -n "317	"; sleep .05
echo -n "331	"; sleep .05
echo -n "337	"; sleep .05
echo -n "347	"; sleep .05
echo  "349	"; sleep .05
echo -n "353	"; sleep .05
echo -n "359	"; sleep .05
echo -n "367	"; sleep .05
echo -n "373	"; sleep .05
echo -n "379	"; sleep .05
echo -n "383	"; sleep .05
echo -n "389	"; sleep .05
echo -n "397	"; sleep .05
echo -n "401	"; sleep .05
echo  "409	"; sleep .05
echo -n "419	"; sleep .05
echo -n "421	"; sleep .05
echo -n "431	"; sleep .05
echo -n "433	"; sleep .05
echo -n "439	"; sleep .05
echo -n "443	"; sleep .05
echo -n "449	"; sleep .05
echo -n "457	"; sleep .05
echo -n "461	"; sleep .05
echo  "463	"; sleep .05
echo -n "467	"; sleep .05
echo -n "479	"; sleep .05
echo -n "487	"; sleep .05
echo -n "491	"; sleep .05
echo -n "499	"; sleep .05
echo -n "503	"; sleep .05
echo -n "509	"; sleep .05
echo -n "521	"; sleep .05
echo -n "523	"; sleep .05
echo  "541	"; sleep .05
echo -n "547	"; sleep .05
echo -n "557	"; sleep .05
echo -n "563	"; sleep .05
echo -n "569	"; sleep .05
echo -n "571	"; sleep .05
echo -n "577	"; sleep .05
echo -n "587	"; sleep .05
echo -n "593	"; sleep .05
echo -n "599	"; sleep .05
echo  "601	"; sleep .05
echo -n "607	"; sleep .05
echo -n "613	"; sleep .05
echo -n "617	"; sleep .05
echo -n "619	"; sleep .05
echo -n "631	"; sleep .05
echo -n "641	"; sleep .05
echo -n "643	"; sleep .05
echo -n "647	"; sleep .05
echo -n "653	"; sleep .05
echo  "659	"; sleep .05
echo -n "661	"; sleep .05
echo -n "673	"; sleep .05
echo -n "677	"; sleep .05
echo -n "683	"; sleep .05
echo -n "691	"; sleep .05
echo -n "701	"; sleep .05
echo -n "709	"; sleep .05
echo -n "719	"; sleep .05
echo -n "727	"; sleep .05
echo  "733	"; sleep .05
echo -n "739	"; sleep .05
echo -n "743	"; sleep .05
echo -n "751	"; sleep .05
echo -n "757	"; sleep .05
echo -n "761	"; sleep .05
echo -n "769	"; sleep .05
echo -n "773	"; sleep .05
echo -n "787	"; sleep .05
echo -n "797	"; sleep .05
echo  "809	"; sleep .05
echo -n "811	"; sleep .05
echo -n "821	"; sleep .05
echo -n "823	"; sleep .05
echo -n "827	"; sleep .05
echo -n "829	"; sleep .05
echo -n "839	"; sleep .05
echo -n "853	"; sleep .05
echo -n "857	"; sleep .05
echo -n "859	"; sleep .05
echo  "863	"; sleep .05
echo -n "877	"; sleep .05
echo -n "881	"; sleep .05
echo -n "883	"; sleep .05
echo -n "887	"; sleep .05
echo -n "907	"; sleep .05
echo -n "911	"; sleep .05
echo -n "919	"; sleep .05
echo -n "929	"; sleep .05
echo -n "937	"; sleep .05
echo  "941	"; sleep .05
echo -n "947	"; sleep .05
echo -n "953	"; sleep .05
echo -n "967	"; sleep .05
echo -n "971	"; sleep .05
echo -n "977	"; sleep .05
echo -n "983	"; sleep .05
echo -n "991	"; sleep .05
echo -n "997	"; sleep .05
echo -n "1009	"; sleep .05
echo  "1013	"; sleep .05
echo -n "1019	"; sleep .05
echo -n "1021	"; sleep .05
echo -n "1031	"; sleep .05
echo -n "1033	"; sleep 2
echo -n "1039	"; sleep .05
echo -n "1049	"; sleep .05
echo -n "1051	"; sleep .05
echo -n "1061	"; sleep .05
echo -n "1063	"; sleep .05
echo  "1069	"; sleep .05
echo -n "1087	"; sleep .05
echo -n "1091	"; sleep .05
echo -n "1093	"; sleep .05
echo -n "1097	"; sleep .05
echo -n "1103	"; sleep .05
echo -n "1109	"; sleep .05
echo -n "1117	"; sleep .05
echo -n "1123	"; sleep .05
echo -n "1129	"; sleep .05
echo  "1151	"; sleep .05
echo -n "1153	"; sleep .05
echo -n "1163	"; sleep .05
echo -n "1171	"; sleep .05
echo -n "1181	"; sleep .05
echo -n "1187	"; sleep .05
echo -n "1193	"; sleep .05
echo -n "1201	"; sleep .05
echo -n "1213	"; sleep .05
echo -n "1217	"; sleep .05
echo  "1223	"; sleep .05
echo -n "1229	"; sleep .05
echo -n "1231	"; sleep .05
echo -n "1237	"; sleep .05
echo -n "1249	"; sleep .05
echo -n "1259	"; sleep .05
echo -n "1277	"; sleep .05
echo -n "1279	"; sleep .05
echo -n "1283	"; sleep .05
echo -n "1289	"; sleep .05
echo  "1291	"; sleep .05
echo -n "1297	"; sleep .05
echo -n "1301	"; sleep .05
echo -n "1303	"; sleep .05
echo -n "1307	"; sleep .05
echo -n "1319	"; sleep .05
echo -n "1321	"; sleep .05
echo -n "1327	"; sleep .05
echo -n "1361	"; sleep .05
echo -n "1367	"; sleep .05
echo  "1373	"; sleep .05
echo -n "1381	"; sleep .05
echo -n "1399	"; sleep .05
echo -n "1409	"; sleep .05
echo -n "1423	"; sleep .05
echo -n "1427	"; sleep .05
echo -n "1429	"; sleep .05
echo -n "1433	"; sleep .05
echo -n "1439	"; sleep .05
echo -n "1447	"; sleep .05
echo  "1451	"; sleep .05
echo -n "1453	"; sleep .05
echo -n "1459	"; sleep .05
echo -n "1471	"; sleep .05
echo -n "1481	"; sleep .05
echo -n "1483	"; sleep .05
echo -n "1487	"; sleep .05
echo -n "1489	"; sleep .05
echo -n "1493	"; sleep .05
echo -n "1499	"; sleep .05
echo  "1511	"; sleep .05
echo -n "1523	"; sleep .05
echo -n "1531	"; sleep .05
echo -n "1543	"; sleep .05
echo -n "1549	"; sleep .05
echo -n "1553	"; sleep .05
echo -n "1559	"; sleep .05
echo -n "1567	"; sleep .05
echo -n "1571	"; sleep .05
echo -n "1579	"; sleep .05
echo  "1583	"; sleep .05
echo -n "1597	"; sleep .05
echo -n "1601	"; sleep .05
echo -n "1607	"; sleep .05
echo -n "1609	"; sleep .05
echo -n "1613	"; sleep .05
echo -n "1619	"; sleep .05
echo -n "1621	"; sleep .05
echo -n "1627	"; sleep .05
echo -n "1637	"; sleep .05
echo  "1657	"; sleep .05
echo -n "1663	"; sleep .05
echo -n "1667	"; sleep .05
echo -n "1669	"; sleep .05
echo -n "1693	"; sleep .05
echo -n "1697	"; sleep .05
echo -n "1699	"; sleep .05
echo -n "1709	"; sleep .05
echo -n "1721	"; sleep .05
echo -n "1723	"; sleep .05
echo  "1733	"; sleep .05
echo -n "1741	"; sleep .05
echo -n "1747	"; sleep .05
echo -n "1753	"; sleep .05
echo -n "1759	"; sleep .05
echo -n "1777	"; sleep .05
echo -n "1783	"; sleep .05
echo -n "1787	"; sleep .05
echo -n "1789	"; sleep .05
echo -n "1801	"; sleep .05
echo  "1811	"; sleep .05
echo -n "1823	"; sleep .05
echo -n "1831	"; sleep .05
echo -n "1847	"; sleep .05
echo -n "1861	"; sleep .05
echo -n "1867	"; sleep .05
echo -n "1871	"; sleep .05
echo -n "1873	"; sleep .05
echo -n "1877	"; sleep .05
echo -n "1879	"; sleep .05
echo  "1889	"; sleep .05
echo -n "1901	"; sleep .05
echo -n "1907	"; sleep .05
echo -n "1913	"; sleep .05
echo -n "1931	"; sleep .05
echo -n "1933	"; sleep .05
echo -n "1949	"; sleep .05
echo -n "1951	"; sleep .05
echo -n "1973	"; sleep .05
echo -n "1979	"; sleep .05
echo  "1987	"; sleep .05
echo -n "1993	"; sleep .05
echo -n "1997	"; sleep .05
echo -n "1999	"; sleep .05
echo -n "2003	"; sleep .05
echo -n "2011	"; sleep .05
echo -n "2017	"; sleep .05
echo -n "2027	"; sleep .05
echo -n "2029	"; sleep .05
echo -n "2039	"; sleep .05
echo  "2053	"; sleep .05
echo -n "2063	"; sleep .05
echo -n "2069	"; sleep .05
echo -n "2081	"; sleep .05
echo -n "2083	"; sleep .05
echo -n "2087	"; sleep .05
echo -n "2089	"; sleep .05
echo -n "2099	"; sleep .05
echo -n "2111	"; sleep .05
echo -n "2113	"; sleep .05
echo  "2129	"; sleep .05
echo -n "2131	"; sleep .05
echo -n "2137	"; sleep .05
echo -n "2141	"; sleep .05
echo -n "2143	"; sleep .05
echo -n "2153	"; sleep .05
echo -n "2161	"; sleep .05
echo -n "2179	"; sleep .05
echo -n "2203	"; sleep .05
echo -n "2207	"; sleep .05
echo  "2213	"; sleep .05
echo -n "2221	"; sleep .05
echo -n "2237	"; sleep .05
echo -n "2239	"; sleep .05
echo -n "2243	"; sleep .05
echo -n "2251	"; sleep .05
echo -n "2267	"; sleep .05
echo -n "2269	"; sleep .05
echo -n "2273	"; sleep .05
echo -n "2281	"; sleep .05
echo  "2287	"; sleep .05
echo -n "2293	"; sleep .05
echo -n "2297	"; sleep .05
echo -n "2309	"; sleep .05
echo -n "2311	"; sleep .05
echo -n "2333	"; sleep .05
echo -n "2339	"; sleep .05
echo -n "2341	"; sleep .05
echo -n "2347	"; sleep .05
echo -n "2351	"; sleep .05
echo  "2357	"; sleep .05
echo -n "2371	"; sleep .05
echo -n "2377	"; sleep .05
echo -n "2381	"; sleep .05
echo -n "2383	"; sleep .05
echo -n "2389	"; sleep .05
echo -n "2393	"; sleep .05
echo -n "2399	"; sleep .05
echo -n "2411	"; sleep .05
echo -n "2417	"; sleep .05
echo  "2423	"; sleep .05
echo -n "2437	"; sleep .05
echo -n "2441	"; sleep .05
echo -n "2447	"; sleep .05
echo -n "2459	"; sleep .05
echo -n "2467	"; sleep .05
echo -n "2473	"; sleep .05
echo -n "2477	"; sleep .05
echo -n "2503	"; sleep .05
echo -n "2521	"; sleep .05
echo  "2531	"; sleep .05
echo -n "2539	"; sleep .05
echo -n "2543	"; sleep .05
echo -n "2549	"; sleep .05
echo -n "2551	"; sleep .05
echo -n "2557	"; sleep .05
echo -n "2579	"; sleep .05
echo -n "2591	"; sleep .05
echo -n "2593	"; sleep .05
echo -n "2609	"; sleep .05
echo  "2617	"; sleep .05
echo -n "2621	"; sleep .05
echo -n "2633	"; sleep .05
echo -n "2647	"; sleep .05
echo -n "2657	"; sleep .05
echo -n "2659	"; sleep .05
echo -n "2663	"; sleep .05
echo -n "2671	"; sleep .05
echo -n "2677	"; sleep .05
echo -n "2683	"; sleep .05
echo  "2687	"; sleep .05
echo -n "2689	"; sleep .05
echo -n "2693	"; sleep .05
echo -n "2699	"; sleep .05
echo -n "2707	"; sleep .05
echo -n "2711	"; sleep .05
echo -n "2713	"; sleep .05
echo -n "2719	"; sleep .05
echo -n "2729	"; sleep .05
echo -n "2731	"; sleep .05
echo  "2741	"; sleep .05
echo -n "2749	"; sleep .05
echo -n "2753	"; sleep .05
echo -n "2767	"; sleep .05
echo -n "2777	"; sleep .05
echo -n "2789	"; sleep .05
echo -n "2791	"; sleep .05
echo -n "2797	"; sleep .05
echo -n "2801	"; sleep .05
echo -n "2803	"; sleep .05
echo  "2819	"; sleep .05
echo -n "2833	"; sleep .05
echo -n "2837	"; sleep .05
echo -n "2843	"; sleep .05
echo -n "2851	"; sleep .05
echo -n "2857	"; sleep .05
echo -n "2861	"; sleep .05
echo -n "2879	"; sleep .05
echo -n "2887	"; sleep .05
echo -n "2897	"; sleep .05
echo  "2903	"; sleep .05
echo -n "2909	"; sleep .05
echo -n "2917	"; sleep .05
echo -n "2927	"; sleep .05
echo -n "2939	"; sleep .05
echo -n "2953	"; sleep .05
echo -n "2957	"; sleep .05
echo -n "2963	"; sleep .05
echo -n "2969	"; sleep .05
echo -n "2971	"; sleep .05
echo  "2999	"; sleep .05
echo -n "3001	"; sleep .05
echo -n "3011	"; sleep .05
echo -n "3019	"; sleep .05
echo -n "3023	"; sleep .05
echo -n "3037	"; sleep .05
echo -n "3041	"; sleep .05
echo -n "3049	"; sleep .05
echo -n "3061	"; sleep .05
echo -n "3067	"; sleep .05
echo  "3079	"; sleep .05
echo -n "3083	"; sleep .05
echo -n "3089	"; sleep .05
echo -n "3109	"; sleep .05
echo -n "3119	"; sleep .05
echo -n "3121	"; sleep .05
echo -n "3137	"; sleep .05
echo -n "3163	"; sleep .05
echo -n "3167	"; sleep .05
echo -n "3169	"; sleep .05
echo  "3181	"; sleep .05
echo -n "3187	"; sleep .05
echo -n "3191	"; sleep .05
echo -n "3203	"; sleep .05
echo -n "3209	"; sleep .05
echo -n "3217	"; sleep .05
echo -n "3221	"; sleep .05
echo -n "3229	"; sleep .05
echo -n "3251	"; sleep .05
echo -n "3253	"; sleep .05
echo  "3257	"; sleep .05
echo -n "3259	"; sleep .05
echo -n "3271	"; sleep .05
echo -n "3299	"; sleep .05
echo -n "3301	"; sleep 2
